name: dozer_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  image_picker: 0.4.10
  date_format: 1.0.5
  serializable: 0.11.0+1
  http: 0.11.3+17
  shared_preferences: 0.4.2

  firebase_auth: 0.5.19
  google_sign_in: 3.0.5
  cupertino_icons: ^0.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

